services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
  consul:
    container_name: consul
    image: consul:latest
    command: >-
      consul
      agent
      -dev
      -log-level=debug
      -recursor=8.8.8.8
      -client=0.0.0.0
      -enable-local-script-checks
    ports:
      - 8500:8500
    restart: always