services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
  jaeger:
    image: jaegertracing/all-in-one:latest
    restart: always
    ports:
      - 6831:6831/udp
      - 6832:6832/udp
      - 16686:16686
  consul-server:
    image: consul:latest
    restart: always
    command: "agent"
    ports:
      - 8500:8500
      - 8600:8600/tcp
      - 8600:8600/udp
    volumes:
     - ./docker-consul-server.json:/consul/config/server.json:ro